# Change baseurl before deploy
# baseurl is now configured dynamically in the build workflow
# baseurl = "https://yikai-liao.github.io/hugo/"

title = "Yikai Liao's Tech Blog" # Please update this title

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

enableRobotsTXT = true # Generate robots.txt

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

# Copyright notice (used in RSS Feed)
copyright = "© 2024 Your Name or Company Name" # Please update this

[params.author]
  name = "Yikai Liao" # Please update this
  email = "lyk-boya@outlook.com" # Please update this

[pagination]
pagerSize = 5

[outputs]
  # Combine outputs from both branches
  home = ["HTML", "RSS", "JSON", "ARTICLES"]
  section = ["HTML", "RSS", "ContentJSON"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats]
  # Keep JSON format (likely for theme's default search)
  [outputFormats.JSON]
    baseName = "index" 
    isPlainText = true
    mediaType = "application/json"
  # Keep ContentJSON format (for AI search build script)
  [outputFormats.ContentJSON]
    mediaType = "application/json"
    baseName = "content" 
    isPlainText = true
    notAlternative = true
  # Define ARTICLES format for our AI search backend
  [outputFormats.ARTICLES]
    mediaType = "application/json"
    baseName = "articles" # This will generate articles.json
    isPlainText = false   # Make sure it handles JSON correctly, not plain text
    notAlternative = true # Don't list in <link rel="alternative">

[services]
  [services.rss]
    # Include all posts in RSS feed
    limit = -1

# --- Proxy config moved to root hugo.toml ---
# [[server.proxy]]
# # Source path on your local server
# from = "/api/ai-search"
# # Target URL of your deployed Cloudflare Worker - TEMPORARILY CHANGED FOR TESTING
# to = "https://httpbin.org/post" # Changed target to httpbin
# # --- End Proxy Configuration ---