# Change baseurl before deploy
# baseurl is now configured dynamically in the build workflow
# baseurl = "https://yikai-liao.github.io/hugo/"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

# Copyright notice (used in RSS Feed)
copyright = "© 2024 Your Name or Company Name" # Please update this

[params.author]
  name = "Your Name" # Please update this
  email = "your.email@example.com" # Please update this

[pagination]
pagerSize = 5

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[services]
  [services.rss]
    # Include all posts in RSS feed
    limit = -1