# 配置主菜单和社交媒体菜单
[[main]]
identifier = "home"
name = "主页"
url = "/zh/"
weight = 1
[main.params]
icon = "home"

[[main]]
identifier = "search"
name = "搜索"
url = "/zh/search/"
weight = 2
[main.params]
icon = "search"

# Add AI Search menu item (Chinese)
[[main]]
identifier = "ai-search"
name = "AI 搜索"
url = "/zh/ai-search/" # Points to the new AI Search page (Chinese version)
weight = 2.5 # Position it after Search
[main.params]
icon = "brain"

[[main]]
identifier = "archives"
name = "归档"
url = "/zh/archives/"
weight = 3
[main.params]
icon = "archives"

[[main]]
identifier = "about"
name = "关于"
url = "/zh/about/"
weight = 4
[main.params]
icon = "user"

[[main]]
identifier = "links"
name = "友链"
url = "/zh/links/"
weight = 5
[main.params]
icon = "link"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Yikai-Liao"
weight = 10

[social.params]
icon = "brand-github"

[[social]]
identifier = "zhihu"
name = "知乎"
url = "https://www.zhihu.com/people/tai-shan-ye-zi"
weight = 20

[social.params]
icon = "brand-zhihu"

[[social]]
identifier = "rss"
name = "RSS"
url = "/zh/index.xml"
weight = 100

[social.params]
icon = "rss"