# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[main.params]
icon = "home"

[[main]]
identifier = "search"
name = "Search"
url = "/search"
weight = 2
[main.params]
icon = "search"

[[main]]
identifier = "ai-search"
name = "AI Search"
url = "/ai-search"
weight = 2
[main.params]
icon = "brain"

[[main]]
identifier = "archives"
name = "Archives"
url = "/archives"
weight = 3
[main.params]
icon = "archives"

[[main]]
identifier = "about"
name = "About"
url = "/about"
weight = 4
[main.params]
icon = "user"

[[main]]
identifier = "links"
name = "Links"
url = "/links"
weight = 5
[main.params]
icon = "link"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Yikai-Liao"
weight = 10

[social.params]
icon = "brand-github"

[[social]]
identifier = "zhihu"
name = "Zhihu"
url = "https://www.zhihu.com/people/tai-shan-ye-zi"
weight = 20

[social.params]
icon = "brand-zhihu"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
weight = 100

[social.params]
icon = "rss"